import 'package:frontend_kusaku/Navigation/History_Kusaku/history_models.dart';

final List<HistoryTransaction> historyDummyTransactions = [
  HistoryTransaction(
    id: 'trx-001',
    title: 'Qris Starbucek',
    amount: -45000,
    occurredAt: DateTime(2026, 2, 28, 9, 45),
    type: HistoryTransactionType.expense,
    category: 'qris',
    channel: 'qris',
  ),
  HistoryTransaction(
    id: 'trx-002',
    title: 'Bensin Pertama',
    amount: -30000,
    occurredAt: DateTime(2026, 2, 28, 8),
    type: HistoryTransactionType.expense,
    category: 'fuel',
    channel: 'merchant',
  ),
  HistoryTransaction(
    id: 'trx-003',
    title: 'eWallet Dimas',
    amount: -200000,
    occurredAt: DateTime(2026, 2, 28, 7, 15),
    type: HistoryTransactionType.expense,
    category: 'transfer',
    channel: 'ewallet',
  ),
  HistoryTransaction(
    id: 'trx-004',
    title: 'Transfer Masuk',
    amount: 2500000,
    occurredAt: DateTime(2026, 2, 28, 6, 30),
    type: HistoryTransactionType.income,
    category: 'transfer',
    channel: 'bank_transfer',
  ),
  HistoryTransaction(
    id: 'trx-005',
    title: 'Qris Kopi Noko',
    amount: -45000,
    occurredAt: DateTime(2026, 2, 27, 18),
    type: HistoryTransactionType.expense,
    category: 'coffee',
    channel: 'qris',
  ),
  HistoryTransaction(
    id: 'trx-006',
    title: 'Bus',
    amount: 8000,
    occurredAt: DateTime(2026, 2, 27, 17, 30),
    type: HistoryTransactionType.income,
    category: 'transport',
    channel: 'cashback',
  ),
  HistoryTransaction(
    id: 'trx-007',
    title: 'Ceritaku Sayang',
    amount: -100000,
    occurredAt: DateTime(2026, 2, 25, 15, 10),
    type: HistoryTransactionType.expense,
    category: 'gift',
    channel: 'merchant',
  ),
];
