# Generated by Django 4.2.29 on 2026-04-03 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBalance',
        ),
    ]
