# Generated by Django 4.2.29 on 2026-03-20 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='image_account',
        ),
    ]
