# Generated by Django 5.2.12 on 2026-03-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='transaction_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
